user nginx;
worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  map_hash_bucket_size 256;
  map_hash_max_size 4092;

  include /etc/nginx/conf.d/*.conf;
}