server {
  listen 80 default_server;
  server_name bl-agents-recrutement.fr www.bl-agents-recrutement.fr;
  resolver 8.8.8.8 1.1.1.1 valid=30s;

  location / {
    return 301 https://weinvest.fr/devenir-agent
  }
}