server {
  listen 80 default_server;
  server_name _;

  # Home
  location = /fr {
    return 301 https://weinvest.fr/;
  }

  # Contact
  location ~ ^/fr/c {
    return 301 https://weinvest.fr/?action=nous-contacter;
  }

  # A propos
  location ~ ^/fr/da/agences-immobilieres/rating {
    return 301 https://weinvest.fr/a-propos-de-nous;
  }

  # Annuaire
  location ~ ^/fr/da/agences-immobilieres {
    return 301 https://weinvest.fr/annuaire;
  }

  location / {
    proxy_pass https://website.vitrinellis.net;
    proxy_set_header Host website.vitrinellis.net;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}