server {
  listen 80 default_server;
  server_name _;

  # Agents (mapping prioritaire)
  if ($agent_redirect != "") {
    return 301 $agent_redirect;
  }

  # Home
  location = /fr {
    return 301 https://weinvest.fr/;
  }
  location = /fr/immobilier-vendu {
    return 301 https://weinvest.fr/;
  }

  # Contact
  location ~ ^/fr/c {
    return 301 https://weinvest.fr/?action=nous-contacter;
  }
  location = /fr/s/www.bloctel.gouv.fr {
    return 301 https://weinvest.fr/?action=nous-contacter;
  }

  # A propos
  location ~ ^/fr/da/agences-immobilieres/rating {
    return 301 https://weinvest.fr/a-propos-de-nous;
  }
  location ~ ^/fr/p/[0-9]+- {
    return 301 https://weinvest.fr/a-propos-de-nous;
  }

  # Annuaire
  location ~ ^/fr/da/agences-immobilieres {
    return 301 https://weinvest.fr/annuaire;
  }
  location ~ ^/fr/du/agents-immobilier {
    return 301 https://weinvest.fr/annuaire;
  }

  # Estimation
  location ~ ^/fr/v/estimation {
    return 301 https://weinvest.fr/estimation-bien?type_offre=1&init=1&type-offre=Achat;
  }

  # Honoraires
  location = /fr/h/honoraires {
    return 301 https://we-invest-assets-bzvkpjyzopz334gep27bqy.s3.eu-west-3.amazonaws.com/20260101_WIF_bareme_d_honaires.pdf;
  }

  # Honoraires
  location = /fr/l/mentions-legales {
    return 301 https://weinvest.fr/mentions-legales/cgu;
  }

  # Politique de confidentialité
  location ~ politique-de-confidentialite/?$ {
    return 301 https://weinvest.fr/mentions-legales/politique-de-confidentialite;
  }

  # Recherche immo
  # Vente
  location = /fr/immobilier-vente {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  location = /fr/s/votre-recherche {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  location ~ ^/fr/sm/immobilier-ven {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  location ~ ^/fr/vendu {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  location ~ ^/fr/vente {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  location ~ ^/fr/programme-neuf {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=1&init=1;
  }

  # Location
  location ~ ^/fr/location {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=2&init=1;
  }

  location ~ ^/fr/immobilier-location {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=2&init=1;
  }

  location ~ ^/fr/sm/immobilier-location {
    return 301 https://weinvest.fr/recherche-immobilier?type_offre=2&init=1;
  }


  location / {
    proxy_pass https://website.vitrinellis.net;
    proxy_set_header Host website.vitrinellis.net;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}