server {
  listen 80 default_server;
  server_name bl-agents.fr www.bl-agents.fr;

  # Home
    location = /fr {
    return 301 https://weinvest.fr/;
  }

  # Contact
     location ~ ^/fr/c {
        return 301 https://weinvest.fr/?action=nous-contacter;
    }

  # A propos
     location ~ ^/fr/da/agences-immobilieres/rating {
        return 301 https://weinvest.fr/a-propos-de-nous;
    }

  # Annuaire
    location ~ ^/fr/da/agences-immobilieres {
    return 301 https://weinvest.fr/annuaire;
}



}